builds:
- env:
  - CGO_ENABLED=1
  - CC=arm-linux-gnueabi-gcc
  main: './src/'
  binary: 'kelele-rain'
  targets:
    - go_first_class
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
