name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install OS build dependencies
        run: |
          sudo apt install -y libasound2-dev gcc-arm-linux-gnueabi
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: false
          cache: true
      - name: Clean go dependencies
        run: |
          go mod tidy
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          distribution: 'goreleaser'
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
